# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-03 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='availability',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='item',
            name='choices',
            field=models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large')], default='s', max_length=1),
        ),
        migrations.AddField(
            model_name='item',
            name='code',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='item',
            name='features',
            field=models.TextField(default='some features'),
        ),
        migrations.AddField(
            model_name='item',
            name='introduction',
            field=models.TextField(default='some intro'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='Give a name', max_length=240),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
