# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-03 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200303_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='availability',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
