# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-18 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20200317_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsize',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemsize',
            name='size',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sizes',
        ),
        migrations.AddField(
            model_name='size',
            name='item',
            field=models.ManyToManyField(related_name='sizes', to='items.Item'),
        ),
        migrations.DeleteModel(
            name='ItemSize',
        ),
    ]
