# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-30 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20200318_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(choices=[('Small', 'sm'), ('Medium', 'md'), ('Large', 'lg')], max_length=3),
        ),
    ]
